// Pins the TS brepstream splitter (src/breps/split.ts) against the SAME
// harness fixture that pins the Lua encoder <-> Go decoder lockstep
// (internal/capture/testdata/harness.brepstream, regenerated by
// tools/brep-harness). The expected numbers below are what the Go reference
// decoder (capture.ConsumeBrep) reports for that fixture — re-derive them
// with the Go test suite when regenerating the fixture.
//
// Run: npm test (tsx --test) from worker/.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { BREP_HEADER, BREPS_WIRE_VERSION, splitBrepstream, type BrepsHead } from "../src/breps/split";

const FIXTURE = new URL("../../internal/capture/testdata/harness.brepstream", import.meta.url);

// Go-reference values for the fixture (from capture.ConsumeBrep; see header).
const REF = {
  gameId: "feed5eed00000000000000000000beef",
  map: "Harness Map 1.0",
  sampleEvery: 30,
  defs: 38,
  teams: 3,
  players: 2,
  frames: 136,
  events: 37,
  firstFrame: 0,
  lastFrame: 4170,
  segments: 2,
  // Bounds of fully-decoded frames; restated-column bounds must sit inside.
  decodedBounds: { minX: 0, maxX: 11580, minZ: 0, maxZ: 10794 },
};

async function gunzip(bytes: Uint8Array): Promise<Uint8Array> {
  const ds = new DecompressionStream("gzip");
  const resp = new Response(new Blob([bytes as BlobPart]).stream().pipeThrough(ds));
  return new Uint8Array(await resp.arrayBuffer());
}

async function headOf(files: Map<string, Uint8Array>, id: string): Promise<BrepsHead> {
  const brw = files.get(`replays/${id}.brw`)!;
  assert.equal(new TextDecoder().decode(brw.subarray(0, 4)), "BRW1");
  assert.equal(brw[4], BREPS_WIRE_VERSION);
  assert.equal(String.fromCharCode(brw[5]), "J");
  const len = new DataView(brw.buffer, brw.byteOffset).getUint32(6, true);
  assert.equal(len, brw.length - 10, "J section spans the rest of the container");
  return JSON.parse(new TextDecoder().decode(await gunzip(brw.subarray(10)))) as BrepsHead;
}

// Independent minimal walker: collects every framed F record and whether it
// is a keyframe, skipping preambles — deliberately re-implemented so a
// slicing bug in the splitter cannot hide from the partition test.
function walkFRecords(data: Uint8Array): { framed: Uint8Array; frame: number; keyframe: boolean }[] {
  const dv = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const out: { framed: Uint8Array; frame: number; keyframe: boolean }[] = [];
  let pos = 0;
  let segments = 0;
  const skipLine = () => {
    const nl = data.indexOf(0x0a, pos);
    pos = nl < 0 ? data.length : nl + 1;
  };
  const skipPreamble = () => {
    segments++;
    skipLine(); // header line
    for (;;) {
      const start = pos;
      const nl = data.indexOf(0x0a, pos);
      const end = nl < 0 ? data.length : nl;
      const line = new TextDecoder().decode(data.subarray(start, end));
      pos = nl < 0 ? data.length : nl + 1;
      if (line.replace(/\r$/, "") === "BRSNAP READY" || pos >= data.length) return;
    }
  };
  skipPreamble();
  while (pos < data.length) {
    if (data[pos] === 0x42) {
      skipPreamble();
      continue;
    }
    if (pos + 5 > data.length) break;
    const tag = data[pos];
    const len = dv.getUint32(pos + 1, true);
    if (pos + 5 + len > data.length) break;
    if (tag === 0x46) {
      const frame = dv.getUint32(pos + 5, true);
      out.push({ framed: data.subarray(pos, pos + 5 + len), frame, keyframe: (data[pos + 5 + 4] & 1) !== 0 });
    }
    pos += 5 + len;
  }
  assert.equal(segments, REF.segments, "fixture segment count");
  return out;
}

test("harness fixture: head matches the Go reference decoder", async () => {
  const data = new Uint8Array(readFileSync(FIXTURE));
  const { gameId, files, warnings } = await splitBrepstream(data);
  assert.deepEqual(warnings, []);
  assert.equal(gameId, REF.gameId);

  const head = await headOf(files, gameId);
  assert.equal(head.format, "breps1");
  assert.equal(head.gameId, REF.gameId);
  assert.equal(head.map, REF.map);
  assert.equal(head.sampleEvery, REF.sampleEvery);
  assert.equal(Object.keys(head.defs).length, REF.defs);
  assert.equal(head.teams.length, REF.teams);
  assert.equal(head.players.length, REF.players);
  assert.equal(head.frameCount, REF.frames);
  assert.equal(head.events.length, REF.events);
  assert.equal(head.chunks[0].frame, REF.firstFrame);
  assert.equal(
    head.chunks.reduce((n, c) => n + c.count, 0),
    REF.frames,
    "chunk counts sum to the emitted frame count",
  );
  for (let i = 1; i < head.chunks.length; i++) {
    assert.ok(head.chunks[i].frame > head.chunks[i - 1].frame, `chunk ${i} frame is monotonic`);
  }
  // Every unit is restated in every keyframe, so the scanned bounds must sit
  // inside the fully-decoded bounds and reach most of the extent.
  const b = head.bounds;
  assert.ok(b.minX >= REF.decodedBounds.minX && b.maxX <= REF.decodedBounds.maxX, `x bounds ${b.minX}..${b.maxX}`);
  assert.ok(b.minZ >= REF.decodedBounds.minZ && b.maxZ <= REF.decodedBounds.maxZ, `z bounds ${b.minZ}..${b.maxZ}`);
  assert.ok(b.maxX > REF.decodedBounds.maxX * 0.9 && b.maxZ > REF.decodedBounds.maxZ * 0.9, "bounds cover the extent");

  // Team playerName backfill mirrors capture.backfillTeamPlayers.
  assert.ok(head.teams.some((t) => t.playerName !== ""), "some team has a display player");
});

test("harness fixture: keys+chunks partition the F records losslessly", async () => {
  const data = new Uint8Array(readFileSync(FIXTURE));
  const { gameId, files } = await splitBrepstream(data);
  const head = await headOf(files, gameId);
  const recs = walkFRecords(data);
  assert.equal(recs.length, REF.frames, "fixture has no stale/duplicate frames");
  assert.equal(recs[recs.length - 1].frame, REF.lastFrame);

  const keyRecs = recs.filter((r) => r.keyframe);
  const deltaRecs = recs.filter((r) => !r.keyframe);
  assert.equal(head.chunks.length, keyRecs.length, "one chunk per keyframe");

  // The keys stream is the framed keyframe records, concatenated in order,
  // sliced at the head's kLen boundaries.
  const keys = await gunzip(files.get(`replays/${gameId}.keys`)!);
  let off = 0;
  for (let i = 0; i < head.chunks.length; i++) {
    const want = keyRecs[i].framed;
    assert.equal(head.chunks[i].kLen, want.length, `chunk ${i} kLen`);
    assert.deepEqual(keys.subarray(off, off + want.length), want, `chunk ${i} keyframe bytes`);
    assert.equal(head.chunks[i].frame, keyRecs[i].frame, `chunk ${i} frame`);
    off += want.length;
  }
  assert.equal(off, keys.length, "keys stream has no extra bytes");

  // Each chunk file is that chunk's framed delta records, concatenated; a
  // chunk with no deltas has no file and len 0.
  let d = 0;
  for (let i = 0; i < head.chunks.length; i++) {
    const nDeltas = head.chunks[i].count - 1;
    const file = files.get(`replays/${gameId}/c${i}`);
    if (nDeltas <= 0) {
      assert.equal(file, undefined, `chunk ${i} has no delta file`);
      assert.equal(head.chunks[i].len, 0);
      continue;
    }
    assert.ok(file, `chunk ${i} delta file exists`);
    assert.equal(head.chunks[i].len, file.length, `chunk ${i} len is the compressed size`);
    const got = await gunzip(file);
    let expect = new Uint8Array(0);
    for (let k = 0; k < nDeltas; k++, d++) {
      const merged = new Uint8Array(expect.length + deltaRecs[d].framed.length);
      merged.set(expect);
      merged.set(deltaRecs[d].framed, expect.length);
      expect = merged;
    }
    assert.deepEqual(got, expect, `chunk ${i} delta bytes`);
  }
  assert.equal(d, deltaRecs.length, "all delta records accounted for");
});

// ---------------------------------------------------------------------------
// Synthetic streams: edge cases the fixture does not cover. buildStream
// hand-encodes records with the format's framing.

function frameRecord(frame: number, keyframe: boolean, units: { id: number; x: number; z: number }[]): Uint8Array {
  const n = units.length;
  const payload = new Uint8Array(10 + n * 22);
  const dv = new DataView(payload.buffer);
  dv.setUint32(0, frame, true);
  dv.setUint8(4, keyframe ? 1 : 0);
  dv.setUint16(5, n, true);
  dv.setUint16(7, 0, true); // nDead
  dv.setUint8(9, 0); // nRes
  units.forEach((u, i) => {
    dv.setUint16(10 + i * 2, u.id, true);
    dv.setUint16(10 + n * 2 + i * 2, 1, true); // def
    dv.setUint8(10 + n * 4 + i, 0); // team
    dv.setInt16(10 + n * 5 + i * 2, u.x, true);
    dv.setInt16(10 + n * 7 + i * 2, u.z, true);
    dv.setUint32(10 + n * 9 + i * 4, 100, true); // hp
    dv.setUint32(10 + n * 13 + i * 4, 100, true); // maxHp
    // dvx/dvz s16 and build u8 stay 0.
  });
  return record(0x46, payload);
}

function record(tag: number, payload: Uint8Array): Uint8Array {
  const out = new Uint8Array(5 + payload.length);
  out[0] = tag;
  new DataView(out.buffer).setUint32(1, payload.length, true);
  out.set(payload, 5);
  return out;
}

const PREAMBLE =
  `${BREP_HEADER}\n` +
  `BRSNAP GID feed5eed00000000000000000000beef\n` +
  `BRSNAP GAME {"map":"Syn Map 1.0","sampleEvery":30,"gameSpeed":30}\n` +
  `BRSNAP DEF {"id":1,"name":"armcom"}\n` +
  `BRSNAP T 0 0 armada #ff0000\n` +
  `BRSNAP P 0 0 0 alice\n` +
  `BRSNAP READY\n`;

function buildStream(...parts: (string | Uint8Array)[]): Uint8Array {
  const enc = new TextEncoder();
  const bytes = parts.map((q) => (typeof q === "string" ? enc.encode(q) : q));
  const out = new Uint8Array(bytes.reduce((n, q) => n + q.length, 0));
  let off = 0;
  for (const q of bytes) {
    out.set(q, off);
    off += q.length;
  }
  return out;
}

test("synthetic: segment restart starts a new chunk; events land in the head", async () => {
  const enc = new TextEncoder();
  const stream = buildStream(
    PREAMBLE,
    record(0x45, enc.encode("25 created 7 1 0")), // event BEFORE any keyframe
    frameRecord(30, true, [{ id: 7, x: 10, z: 20 }]),
    frameRecord(60, false, [{ id: 7, x: 15, z: 20 }]),
    record(0x45, enc.encode("70 destroyed 7 1 0")),
    PREAMBLE, // widget re-enabled: appended segment
    frameRecord(120, true, [{ id: 9, x: -5, z: 40 }]),
    record(0x58, enc.encode("gameover")),
  );
  const { gameId, head, files, warnings } = await splitBrepstream(stream);
  assert.deepEqual(warnings, []);
  assert.equal(gameId, "feed5eed00000000000000000000beef");
  assert.equal(head.frameCount, 3);
  assert.equal(head.endReason, "gameover");
  assert.deepEqual(
    head.chunks.map((c) => ({ frame: c.frame, count: c.count })),
    [
      { frame: 30, count: 2 },
      { frame: 120, count: 1 },
    ],
  );
  assert.deepEqual(head.events, [
    { frame: 25, kind: "created", id: 7, def: 1, team: 0 },
    { frame: 70, kind: "destroyed", id: 7, def: 1, team: 0 },
  ]);
  assert.deepEqual(head.bounds, { minX: -5, maxX: 15, minZ: 20, maxZ: 40 });
  // Chunk 0 has one delta; chunk 1 (single keyframe) has none. Events are
  // not re-served in chunk files.
  assert.ok(files.has(`replays/${gameId}/c0`));
  assert.ok(!files.has(`replays/${gameId}/c1`));
  const c0 = await gunzip(files.get(`replays/${gameId}/c0`)!);
  assert.deepEqual(c0, frameRecord(60, false, [{ id: 7, x: 15, z: 20 }]));
});

test("synthetic: truncated tail record is dropped with a warning", async () => {
  const whole = buildStream(PREAMBLE, frameRecord(30, true, [{ id: 7, x: 1, z: 2 }]), frameRecord(60, false, [{ id: 7, x: 9, z: 2 }]));
  const cut = whole.subarray(0, whole.length - 3);
  const { head, warnings } = await splitBrepstream(cut);
  assert.equal(head.frameCount, 1);
  assert.equal(head.chunks.length, 1);
  assert.equal(head.chunks[0].count, 1);
  assert.ok(warnings.some((w) => w.includes("truncated")), `warnings: ${warnings}`);
});

test("synthetic: overlapping segment frames are served but not counted", async () => {
  const stream = buildStream(
    PREAMBLE,
    frameRecord(30, true, [{ id: 7, x: 1, z: 2 }]),
    frameRecord(60, false, [{ id: 7, x: 2, z: 2 }]),
    PREAMBLE,
    frameRecord(60, true, [{ id: 7, x: 2, z: 2 }]), // stale: <= last emitted
    frameRecord(90, false, [{ id: 7, x: 3, z: 2 }]),
  );
  const { head, warnings } = await splitBrepstream(stream);
  assert.ok(warnings.some((w) => w.includes("overlaps")), `warnings: ${warnings}`);
  assert.equal(head.frameCount, 3); // 30, 60, 90 — the second 60 not counted
  assert.deepEqual(
    head.chunks.map((c) => ({ frame: c.frame, count: c.count })),
    [
      { frame: 30, count: 2 },
      { frame: 60, count: 1 }, // stale keyframe still anchors its chunk
    ],
  );
});

test("synthetic: a stream without a GID is rejected", async () => {
  const noGid = buildStream(PREAMBLE.replace(/BRSNAP GID .*\n/, ""), frameRecord(30, true, []));
  await assert.rejects(() => splitBrepstream(noGid), /no GID/);
});

test("synthetic: not a brepstream is rejected", async () => {
  await assert.rejects(() => splitBrepstream(new TextEncoder().encode("BRP1 nonsense")), /not a brepstream/);
});
